import React from 'react';
import { Styles } from "../styles/TermsOfUse";
import { useStyles, Button } from '@rootzjs/ui';

const Component = ({
      classes,
      onCloseClick
}) =>
      <div className={classes.root}>
            <div className={classes.panel}>
                  <div className={classes.titleContainer}>
                        <span className={classes.title}>Terms of Use</span>
                  </div>
                  <div className={classes.bodyContainer}>
                        <p>This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
                        <div className={classes.sectionHead}>Exclusive to Star Employees</div>
                        <p>Star India Private Limited and its affiliates (“Company”) is providing PRISM (website and mobile application) (“Site”) for use only by its employees only to perform activities that form part of business research, analysis and reporting. The activities include data access, analysis, diagnosis, exploration and internal sharing and communication. (“Purpose”)</p>
                        <div className={classes.sectionHead}>Your Agreement</div>
                        <p>By visiting this Site you are confirming that you are an employee of the Company. Your use of the Site is subject to all applicable policies of the Company including but not limited to 21st Century Fox Principles Governing Electronic Communications, Twenty-First Century Fox End User Information Protection policy, 21st Century Fox Standards of Business Conduct, Star India BU Corporate Governance Policies and Procedures and the Employee Handbook of Star India. The Company reserves the right to change the Terms of Use at any time and will post any such changes here.</p>
                        <div className={classes.sectionHead}>Confidential Policy</div>
                        <p>All information provide on this Site is confidential and shall only be used for the said Purpose if authorized. You will not misuse the information you access on this Site, including without limitation, copying or sharing the information for any unauthorized purpose by any means. Any misuse of this information shall result in disciplinary action or any legal action that the Company may deem fit</p>
                        <p>Your unique user ID and password for accessing this Site are personal to you and confidential. You are responsible for the security and proper use of your unique ID and password that you enter while using the Site and must take all necessary steps to ensure that they are kept confidential, used properly, and not disclosed to unauthorized people.</p>
                        <div className={classes.sectionHead}>Rights to Terminate</div>
                        <p>The Company reserves the right to terminate access to any user at any time for any reason.</p>
                        <div className={classes.sectionHead}>Contact Us</div>
                        <p>In case of any queries, please contact Star IT security team at it.security@startv.com</p>
                  </div>
                  <div className={classes.btnContainer}>
                        <Button text="Close" variant="outlined" onClick={onCloseClick} />
                  </div>
            </div>
      </div>

export const TermsOfUse = useStyles(Styles)(Component)